### ISSUE TITLE
Concern with IG Note

### ISSUE THREAD

**Issue by hlflanagan** [w3c/dpub-pwp-ucr#83] opened 2016-09-13 22:33 UTC
Is this really the only instance where this note applies?
"The Interest Group recognizes that the proper definition/implementation of this requirement may lead to major technical complications and therefore may not be fulfilled." --http://w3c.github.io/dpub-pwp-ucr/#r_manifest-comb

It stands out as very unusual in the text.

**Comment by iherman** [comment] 2016-09-14 09:50
Yeah... this is certainly one of the areas where we _know_ we would have major technical problems. There may indeed be others...

**Comment by TzviyaSiegman** [comment] 2016-09-27 20:40
I think this issue is somewhat unique in that it is an area we KNOW will be a problem. Perhaps we should explain WHY. This goes to issues of origin and security policies.

**Comment by TzviyaSiegman** [comment] 2016-09-27 20:42
@marcoscaceres would you be interested in proposing language about why this is an issue?

**Comment by dauwhe** [comment] 2016-09-27 20:54
I certainly see the utility of creating new works from portions of old works. And I've had to assemble numerous "omnibus" editions, combining several EPUBs into one big EPUB. And it's an enormous pain. But in all these cases I think of myself of creating a new publication, with the age-old technology of cut-and-paste. So I'm wondering what the actual requirement is here. If, indeed, a manifest becomes a requirement, would one manifest import another? Would two manifests be able to be combined without human intention? The use case listed seems more about someone editing an existing manifest, although it could be more generally framed as just adding metadata to an existing publication.

**Comment by marcoscaceres** [comment] 2016-09-28 04:09
> @marcoscaceres would you be interested in proposing language about why this is an issue?

I suggest just dropping this. 

Duplicate of https://github.com/w3c/dpub-pwp-ucr/issues/129

**Comment by iherman** [comment] 2016-09-28 10:06
I think the original question of @hlflanagan is whether this is the only use case in the document that should have this special treatment and, I believe, the answer is yes, insofar as all the other requirements seem like realizable either in current technologies or a foreseeable extension thereof. 

The issue for this specific requirement is indeed discussed further at #129. Maybe the best is to close this issue and use that one for further discussions (or vice versa, I do not really mind either way...).

**Comment by iherman** [comment] 2016-10-13 10:40
Closing in favor of #129

**Closed as completed by iherman** 2016-10-13 10:40 UTC
