### ISSUE TITLE
Assumptions about web history

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#87] opened 2016-09-14 01:37 UTC
>  This model inherited very little from an existing, powerful and much older page-based media: book

Håkon Wium Lie's [PhD thesis](http://people.opera.com/howcome/2006/phd/), which underpins CSS, strongly contradicts the above - particularly from a historical perspective. There was significant influence from print media, and books in particular, in the design of the web and particularly as it relates to layout.

**Comment by iherman** [comment] 2016-09-14 07:00
I agree that this formulation is a bit misleading, but I am not sure we are really disagreeing. The UCR document has, actually, very little on CSS issues. Not because the CSS requirements are not relevant, far from it, but because there is already an active work happening at the CSS WG, and strong relationships between the CSS WG and the DPUB IG, so it seemed superfluous to refer to these here. I guess that the reference in this text is more on the issues, in general, of content organization, addressing, etc, and not on layout.

I agree this has to be made clearer. And maybe a reference to Håkon's PhD is in order.

Cc: @BorisAnthony

**Comment by sideshowbarker** [comment] 2016-09-14 08:19
I think many people would disagree with the assertion “This model inherited very little from an existing, powerful and much older page-based media: book”. Web resources were called “pages” from early on, and the entire in-memory model that we use for Web applications is the “Document Object Model”, and on and on.

Regardless, the statement is at best unnecessary in this document, and likely more distracting and unhelpful in practice than whatever purpose it was intended to serve. So it would seem best to remove it.

**Comment by marcoscaceres** [comment] 2016-09-14 08:22
Agree with Mike. Web ol' timers will get distracted and start citing PhDs at you.

**Comment by BorisAnthony** [comment] 2016-09-25 15:18
Gentlemen,
Somewhat puzzled by this. I've just reread Hakon's PhD. I do not see how it contradicts the statement at all.

The string "book" appears 20 times in the paper, most of those referring to specific books and only twice to the concept of a book, and there purely as an illustration from other domains (general theory & LaTeX) of "structured documents." There is no evidence nor mention of the concept of a "bounded collection of media" as a native-to-the-web object. The only—and naturally tremendous—inspiration this paper on CSS, and CSS in general, garners from books is their rich tradition of page layout and style… but not the concept nor structure of books themselves. (This would have been out of scope for a paper about CSS anyways.)

Pages are not books. The dominant model of the web was "pages" ("documents", hence the DOM), not bundles, collections, packages etc… (see also https://pbs.twimg.com/media/Cs8fNMyXYAE3hMN.jpg )

Besides, the "proof is in the pudding": there is no existing (surviving?) model, concept or specification, at the W3C or elsewhere, for "books on the web" and the work of the DPUB IG is precisely this.

The statement you take issue with is not incorrect and the purpose it serves is to clearly differentiate the concept of books from anything currently represented on the web (pages, sites, apps). It may be a bit polemic, but I rather see it as critical thinking: it may force a reexamination of some closely held beliefs…

p.s.: I've been on and of the Web—both building and theorising about it—since 1995. Does that qualify me as enough of an "old-timer"? ;)

**Comment by TzviyaSiegman** [comment] 2016-11-09 15:32
Please propose alternate language, or we'll leave as is. cc/@sideshowbarker, @marcoscaceres

**Comment by marcoscaceres** [comment] 2016-11-10 05:33
Proposal is to remove that text. It's unnecessarily provocative.

**Comment by TzviyaSiegman** [comment] 2016-11-10 17:53
@BorisAnthony Are you OK with removing this sentence?

**Comment by mattgarrish** [comment] 2016-11-17 04:18
If you drop that sentence, the brief history of web pages to web sites that precedes is disconnected from the following paragraphs and should go, too.

What bothers me about the section, with or without that particular sentence, is that it doesn't really address what this work seeks to achieve by only stating a desire to merge print and digital.

It might be better if, instead of the current vague statement of lost power, it listed some of the ways that books differ from the web page/site model: the seamless binding of multiple pages into a single publication, or the ability to easily collect and store books in a way that is independent of the host of any one site or of one's connectivity.

Something else for you to chew on, anyway.

I saw this also while looking at the dpub-pwp document, but assuming you'll copy over whatever changes you make here.

**Comment by atyposh** [comment] 2018-05-07 15:27
I agree with @BorisAnthony and @mattgarrish. We're all working on WP specifications because the W3C doesn't already have them. Suggesting that the early designers of the Web didn't consider binding webpages into books is hardly provocative (but this old-timer is never sure what will provoke folks these days). 

The first paragraph of the introduction (including the sentence under discussion here) is perfect, IMO. I certainly couldn't have summed up why we're doing this any better. Let's leave it alone. We have bigger fish to fry.

Thoughts?

**Comment by marcoscaceres** [comment] 2018-05-08 03:46
If you leave it, it shows the group didn't do background research (or doesn't understand the Web) and the document instantly loses all fundamental credibility. If you acknowledge, using @sideshowbarker's words:
> "Web resources were called “pages” from early on, and the entire in-memory model that we use for Web applications is the “Document Object Model”, and on and on." 

And then expand, "However, despite the web's strong connections to print media, this document argues that the the web platform may still not be meeting the certain requirements inherent in print media, or features from print media that users desire." 

Something like the above. But seriously, that one sentence undermines the whole document.

**Comment by sideshowbarker** [comment] 2018-05-08 04:40
> Please propose alternate language, or we'll leave as is. cc/@sideshowbarker, @marcoscaceres

So the concrete proposal is: Drop this sentence:

> This model inherited very little from an existing, powerful and much older page-based media: books.

…and replace it with this:

> Web resources were called “pages” from early on, and the entire in-memory model that we use for Web applications is the “Document Object Model”, and on and on. However, despite the Web's strong connections to print media, this document argues that the web platform may still not be meeting the certain requirements inherent in print media, or features from print media that users desire.

…or with some similar formulation which achieves the purpose of not categorically stating the model of the web inherited very little from books despite all the observable evidence at hand that indicates otherwise (early use of the term “pages”, “Document Object Model”, and plenty of other stuff).

You otherwise risk making readers who are aware of that evidence just think you don’t understand what you’re talking about — and make them wonder what other inaccuracies or misconceptions might be waiting in the rest of the document.

**Comment by marcoscaceres** [comment] 2018-05-08 04:43
(just noting I made a typo "the the" - but 👍 to @sideshowbarker's proposal)

**Comment by sideshowbarker** [comment] 2018-05-08 04:44
> just noting I made a typo "the the"

Fixed

**Comment by atyposh** [comment] 2018-05-21 15:53
In deference to those who feel strongly about this, I propose the following (slight) amendment:

Drop this sentence:

> This model inherited very little from an existing, powerful and much older page-based media: books.

…and replace it with this:

> Despite the Web's strong connections to print media (_e.g._ web resources are “pages” and the in-memory model for Web applications is the “Document Object Model”), this document argues that the web platform may still not be meeting certain requirements from print media that users desire.

**Comment by marcoscaceres** [comment] 2018-05-21 16:20
I’m ok with the proposed text by @atyposh.

**Comment by sideshowbarker** [comment] 2018-05-21 23:16
> I’m ok with the proposed text by @atyposh.

Looks OK to me too

**Closed as completed** 2018-06-18 20:47 UTC
